### ISSUE TITLE
Cannot create labels on Funnel chart 

### ISSUE THREAD

**Issue by Junaid-Sakib** [numetriclabz/numAndroidCharts#1]
Hi, thanks for the lib - great work! 

I am not able to see the labels for funnel chart: 

values.add(new ChartData("visits", 3000));
values.add(new ChartData("unique visits", 2000));
values.add(new ChartData("unique visitors", 1000));
values.add(new ChartData("unique session", 500));
values.add(new ChartData("log out", 400));

I am using the above code to render it. Exactly like it is done in the tutorial. However as the other factors seem to work, the labels are not to be seen.

**Comment by uditsingh1** [comment]
Hi Junaid,

You need to use the latest version of the library. Add the below line in your app build.gradle file's dependency : 
 'com.numetriclabz.numandroidcharts:numandroidcharts:1.0.19'

**Comment by Junaid-Sakib** [comment]
Thanks a lot mate, it works like a charm now :)

**Comment by Junaid-Sakib** [comment]
One Small issue, when I show and hide the view the legend replicates itself +1 times giving me a grid of square boxes and text. 

Code: 

```
case R.id.radioFunnel:
                        chart_enquiries.setVisibility(View.GONE);
                        funnelChart.setVisibility(View.VISIBLE);
                        break;


```

Result:

![screenshot_2016-02-04-15-59-57](https://cloud.githubusercontent.com/assets/2277426/12812575/c5c4e7e6-cb58-11e5-9375-dfcbfc40232b.png)

**Comment by uditsingh1** [comment]
Junaid,

Thanks for pointing out the issue. Change the library version to 1.0.20.

**Comment by Junaid-Sakib** [comment]
Thanks a ton Udit, 

Cant express in words how helpful this has been :) 

Power to your code!

**Comment by wcchoong** [comment]
May I know how to display the values in the chart?
